version: '3.8'

services:
  receive:
    image: ghcr.io/argaman123/data-courier:latest
    environment:
      - ENV_FOR_DYNACONF=receive
    volumes:
      - ./external/output:/app/external/output
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 256000000
