version: '3.8'

services:
  send:
    image: ghcr.io/argaman123/data-courier:latest
    environment:
      - ENV_FOR_DYNACONF=send
    volumes:
      - ./external/input:/app/external/input
      - ./external/temp:/app/external/temp
      - ./src:/app/src
      - ./resources:/app/resources