version: '3.8'

services:
  sende:
    image: data-courier:latest
    command: [ "python", "-m", "src.send.main" ]
    deploy:
      mode: replicated
      replicas: 1

    volumes:
      - ./external/input:/app/input
      - ./external/temp:/app/temp
