[default]
log_level = 'INFO'
ip = '192.168.1.2'
port = 55555

# Higher values affect the chunk size (and therefore, greatly increase the padding of tiny files),
#   and require a restart on both ends.
payload_size = 1_400 # Bytes of file data per packet. A value under 1.5KB would help prevent IP fragmentation