[default]
log_level = 'INFO'
socket.ip = '192.168.1.2'
socket.port = 55555
socket.buffer_size = 256_000_000 # Maximum bytes the OS can hold for the network card

payload_size = 1_400 # Bytes of file data per packet; kept under 1.5KB to prevent IP fragmentation